meta_product_name: "HANDIC'APPS"
meta_title: "HANDIC'APPS - Une route sans étape"
meta_description: "Une plateforme dédié aux aidants pour les accompagner dans les demarches administratives relatives au handicap."
meta_image: "og_image.png" # should exist in `app/assets/images/`
